# Generated by Django 5.2.1 on 2025-06-09 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_02_task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='task',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(help_text='Категории, к которым относится задача', related_name='tasks', to='hw_02_task_manager.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(error_messages={'unique_for_date': 'Это название уже используется для сегодняшней даты. Введите другое название.'}, help_text='Введите название задачи, иначе будет присвоено название по умолчанию Task+Number', max_length=50, unique_for_date='publish_date', validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название задачи'),
        ),
    ]
