# Generated by Django 5.2.1 on 2025-06-24 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_02_task_manager', '0003_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Категория выполнения', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(blank=True, help_text='Отдельная часть основной задачи', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(help_text='Категории, к которым относится задача', related_name='tasks', to='hw_02_task_manager.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(error_messages={'unique_for_date': 'Это название уже используется для сегодняшней даты. Введите другое название.'}, help_text='Введите название задачи, иначе будет присвоено название по умолчанию Task+Number', max_length=50, unique_for_date='publish_date', validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
